#spring.application.name=backend-springboot
#
#server.port=8080
#
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/resource_management
#spring.datasource.username=root
#spring.datasource.password=Pr01299
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.main.allow-bean-definition-overriding=true
#
## JWT Configuration (86400000 ms = 1 day)
#app.jwt.secret=your-super-secure-32-character-minimum-secret-key!
#app.jwt.expiration-milliseconds=86400000

spring.application.name=backend-springboot

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/resource_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.main.allow-bean-definition-overriding=true

# JWT Configuration
app.jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290IiwiaWF0IjoxNzQ4NzY0MzQ0LCJleHAiOjE3NDg4NTA3NDR9.V22nL94-wW56V4bJtP7l6c9Y1962O8u5bY5y9b8r4y0
app.jwt.expiration-milliseconds=86400000

# Python ML Service Configuration
ml.service.url=http://localhost:8000